### ISSUE TITLE
Exercise 4: GIT Branches

### ISSUE THREAD

**Issue by duynguyenx** [NT-Line-team/Behave_test#6]
When developing a new feature, it is considered a good practice to work on a copy of the original project, called a branch. Branches have their own history and isolate their changes from one another, until you decide to merge them back together. This is done for a couple of reasons:

An already working, stable version of the code won’t be broken.
Many features can be safely developed at once by different people.
Developers can work on their own branch, without the risk of their codebase changing due to someone else’s work.
When unsure what’s best, multiple versions of the same feature can be developed on separate branches and then compared.

## Creating new branches – `git branch`

The default branch of every repository is called master. To create additional branches use the git branch <name> command:

`$ git branch amazing_new_feature`
This just creates the new branch, which at this point is exactly the same as our master.

## Switching branches –` git checkout`

Now, when we run git branch,  we will see there are two options available:

```
$ git branch
  amazing_new_feature
* master
```
Master is the current branch and is marked with an asterisk. However, we want to work on our new amazing features, so we need to switch to the other branch. This is done with the git checkout command, expecting one parameter – the branch to switch to.

`$ git checkout amazing_new_feature`

## Merging branches – `git merge`

Our “amazing new feature” is going to be just another text file called feature.txt. We will create it, add it, and commit it.

```
$ git add feature.txt
$ git commit -m "New feature complete."
```
The new feature is complete, we can go back to the master branch.

`$ git checkout develop`
Now, if we open our project in the file browser, we’ll notice that feature.txt has disappeared. That’s because we are back in the master branch, and here feature.txt was never created. To bring it in, we need to git merge the two branches together, applying the changes done in amazing_new_feature to the main version of the project.

```
git merge amazing_new_feature
The master branch is now up to date. The awesome_new_feature branch is no longer needed and can be removed.
```

`git branch -d amazing_new_feature`

**Comment by sunguyenhuu** [comment]
For fully GIT command, we can review detail if needed via link https://bueltge.de/git/
or http://guides.beanstalkapp.com/version-control/common-git-commands.html#local

Hope they will be useful. 

Thanks,
